### ISSUE TITLE
build instruction

### ISSUE THREAD

**Issue by Kashouryo** [gabonator/LA104#16]
it'll be absolutely helpful to have a building guide for linux and windows

**Comment by gabonator** [comment]
Please check this and let me know if it helped:
https://github.com/gabonator/LA104/tree/master/resources/tutorial_building

.. and of course feel free to contribute and add missing parts or improve unclear steps

**Comment by Kashouryo** [comment]
Thank you! That helped a lot! I am building on Ubuntu and the info is really helpful!
