### ISSUE TITLE
[Fatal error] Unable to build binary: "STM32F10x.h" No such file or directory

### ISSUE THREAD

**Issue by Kashouryo** [gabonator/LA104#17]
Build log: https://glot.io/snippets/fpjuu9wtuh
I am building it on ubuntu 20.04 x64 with the newest arm compiler. I am following the instruction in the resources folder.

Also, it'll be way better to use a CI to generate the latest pre-built binaries.
Thank you!

**Comment by gabonator** [comment]
some files have wrong names. you will need to fix the file name case either in includes or rename them. I am building on osx which is case insensitive, so I need someone with linux machine to find out which files need to be renamed (I think there are just two of them) and to make pull request with those changes.

I am not familiar with github CI, but if you can give mi hints how to configure it with arm eabi toolchain, I can give it a try
