### ISSUE TITLE
Official App does not show names of all signals

### ISSUE THREAD

**Issue by kontakt** [gabonator/LA104#2]
The official app only shows the first signal name on the signals list, i.e. SPI input mode shows only 1: MOSI and 2:4 are empty.

**Comment by gbraad** [comment]
I have the same behaviour... :-/ Didn't see this in the original firmware

**Comment by gabonator** [comment]
fixed in https://github.com/gabonator/LA104/commit/98ec7b675177c284e76bfaf632be93ee87cc73e5
