### ISSUE TITLE
DS213 running multiple firmwares?

### ISSUE THREAD

**Issue by dejanmilivojevic** [gabonator/LA104#21]
Hi, 

In the docs of ds213 they state that you have 4 app partitions for running multiple apps. Is it possible too run this firmware side by side with the official one. If so, how?

Thanks.

**Comment by gabonator** [comment]
It could be possible, but it is not planned. The idea behind this project is to have one operating system that will allow easy runtime switching between other apps. The original fw was already ported to be used by this OS, see the release packages
