### ISSUE TITLE
Sequencer doesn't work in lateste Beta

### ISSUE THREAD

**Issue by wbvreeuwijk** [gabonator/LA104#24]
Hi,

First of all, thanks for creating this project. It makes these devices even more useful than they already are.
I recently installed the beta release, and most of the apps work; however, the sequencer app appears not to accept the SMPLbutton on the menu. So I'm not able to get into settings or select Loop, Burst, or Follow.

Since it is a beta release, this may already be on your radar; if so, then please ignore this message :-)

**Comment by gabonator** [comment]
Thank you very much for testing and reporting this issue. I fixed it in this commit: https://github.com/gabonator/LA104/commit/cba00e61ee7843a6dc025f4df2b010d4377f3306

you can download fixed version here:
https://github.com/gabonator/LA104/blob/master/system/release/bin/22seqen.elf

**Comment by wbvreeuwijk** [comment]
Thanks.

I'm now able to select the Loop and Follow functions. The settings and File options don't work for me yet however. Als when trying to exit the application I get the Press F1 to retry message and 'shell.elf' not found error.

**Comment by gabonator** [comment]
Please try this update:
[sequencer_update2.zip](https://github.com/gabonator/LA104/files/5434343/sequencer_update2.zip)

You will need two PCF8574 I2C expanders to use this app, otherwise it will work in offline mode. I added there notification messages and removed unimplemented menu tabs

**Comment by wbvreeuwijk** [comment]
Thanks.

This is working. I tested with two PCF8574's I had laying around. One thing that may be useful to add to these apps is how to connect and what addresses to set the PCF8574 to. I had to look at the code to figure this out. Maybe a short Readme.md.
Another useful feature would be to be able to set the speed.

**Comment by gabonator** [comment]
Added short manual for those applications:
![gui3](https://user-images.githubusercontent.com/1020041/97338551-d0ed6a00-1881-11eb-894f-6ee246f4e515.png)
![gui4](https://user-images.githubusercontent.com/1020041/97338559-d34fc400-1881-11eb-9d85-6d73f4902fed.png)
![view](https://user-images.githubusercontent.com/1020041/97338570-d5b21e00-1881-11eb-9ab5-be01eaf81cdb.png)
