### ISSUE TITLE
About the problem that the .hex file cannot be copied under the windows system.

### ISSUE THREAD

**Issue by BG7UHS** [gabonator/LA104#42]
The problem has been solved, if you encounter this problem, please refer to it.
Like the product manual, copying a single .hex will get stuck and cannot be copied.
We need to copy two files (.hex file and any blank text file). After copying, the extension of both files will become .err files.  At this time, delete the blank text file and change the firmware .err extension to .hex.  We will get the .rdy file.

**Comment by gabonator** [comment]
https://github.com/gabonator/LA104/discussions/45
