### ISSUE TITLE
DS203 2020.11.4 release shell.elf Assertion failed

### ISSUE THREAD

**Issue by erik-smit** [gabonator/LA104#50]
I have a DSO Quad DS203 V2.7

When starting shell.elf I get the error: `Symbol '_ZN4BIOS3SYS12GetAttributeENS0_10EAttributE' not found!`.

* I suspect this is because my install with dfuload gives an error.
```
$ ./dfuload /dev/sdb cp ~/Downloads/system_ds203.hex 
Opening: '/dev/sdb' .....................................................
Failed to open disk '/dev/sdb', errno:13
```

* Copy .hex with W10 also fails. 
* Copy .hex with mtools gives no error:

```
[smite@ErikXPS13 dfuload]$ sudo mcopy -i /dev/sdb ~/Downloads/system_ds203.hex ::system_ds203.hex
[smite@ErikXPS13 dfuload]$ sudo mdir -i /dev/sdb
 Volume in drive : is DFU V3_11_C
Directory for ::/

SYSTEM~1 RDY     74413 2021-03-11  15:21 
        1 file               74 413 bytes
```
But still same error.

* I've also tried release 2019.12. Here, shell.elf works, but webosc.elf gives the same assertion failed, symbol not found.

* My DFU is the famous V3.11C. Is this "symbol not found" caused by install not fully completing?
I've tried flashing STM32 via UART, but have not been succesful so far.
When I connect the Rx/Tx as indicated, both stm32flasher and "Flash Loader Demo" get no response from the device.
When I reverse them, stm32flasher still can't init. "Flash Loader Demo" says it sees an unknown device.
When testing with a terminal emulator in reversed state, I get _some_ response on my input.
When testing with a terminal emulator in indicated state, I get no response on my input.

Should I continue to try to upgrade or downgrade my DFU?
Is there a non-UART way to do so?

**Comment by gabonator** [comment]
symbol not found means you have different version of system (firmware hex file) and application (shell.elf). Download newest package from releases. regarding the problems with fw upload - try to use the dfuload tool. Error 13 means permission denied, so try sudo dfuload...

**Comment by erik-smit** [comment]
Ohhh, the progressbar as dots with dfuload made me think it was writing, but it was not.
It's ok now, thank you!
