### ISSUE TITLE
test41_alchemy corrupts filesystem

### ISSUE THREAD

**Issue by nieldk** [gabonator/LA104#55]
been testing test41_alchemy, which is a cool app, so thank you for that.

But, it corrupts the fikesystem, to a degree, where it ends up 'empty' - eg needs to reformat, and reinstall all.

it happens, when pressing F3, a file rf00x.sig is reported saved, with OK message.

but, when rebooting the device, there is nothing on the disk, and reinstall is necessary.

**Comment by gabonator** [comment]
Should be fixed here: https://github.com/gabonator/LA104/commit/6e852913ca90b7fb823c2b3d9fdb252aea18b870
could you please verify if it is ok?

**Comment by nieldk** [comment]
fixed it.
closing :) and thanks
