### ISSUE TITLE
OS port to ESP32

### ISSUE THREAD

**Issue by ricardojlrufino** [gabonator/LA104#91]
I was looking for a while ago something like this for ESP32. Is it possible to implement dynamic loading of applications in it?

**Comment by 203Null** [comment]
It is possible via https://github.com/niicoooo/esp32-elfloader
I'm currently trying to make something like this OS on my esp32 hardware

**Comment by ricardojlrufino** [comment]
nice !!

**Comment by gabonator** [comment]
@203Null thank you for reporting this, my elf loader is extremely simple and does not take relocations into account for the sake of simplicity and reliability. Full relocation support would be nice improvement in this project
