### ISSUE TITLE
Error loading the system_la104.hex of 2022.12.12

### ISSUE THREAD

**Issue by g5pw** [gabonator/LA104#98]
I'm having issues loading the new system_la104.hex, downloaded from the latest release. I tried:

- using `dd` with fsync
- using the `dfutool`
- formatting using `format.sh` and retrying

to no avail, I always get the .err file :( Is there some way to get more info out of it?

**Comment by gabonator** [comment]
Copy it using regular `cp` command, wait for device reconnect. Just ignore that err file and copy it again with `cp`

**Comment by g5pw** [comment]
Huh, that worked. Thanks!
